# yaml 配置
version: '3'
services:
  nginx:
    image: anroe/nginx-headers-more:latest
    # 端口映射
    ports:
      - "8080:8080"
    # 依赖关系 先跑php
    depends_on:
      - "php"
    # 数据卷
    volumes:
      # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
      - "./nginx:/etc/nginx/conf.d"
      - "./html:/usr/share/nginx/html"
    networks:
      - app_net
        # 容器名称
    container_name: "compose-nginx"
  php:
    build: ./php
    # image指定build Dockerfile生成镜像的名称
    image: php:7.2-fpm-mysqli
    ports:
      - "9000:9000"
    volumes:
      - "./html:/var/www/html"
    networks:
      - app_net
    container_name: "compose-php"
  mysql:
    image: mysql:1
    container_name: mysql
    build: ./mysql
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=adminermysql
    ports:
      - "3306:3306"
    networks:
      app_net:
        # 固定子网ip，网段必须在子网络10.10.*.*
        ipv4_address: 10.10.10.2
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-file /docker-entrypoint-initdb.d/test.sql
  worker:
    build: ./src
    command: python3 cron.py
    command: /bin/bash -c "mkdir ./result_pic && mkdir ./result_pic/pics && cd ./result_pic && python3 -m http.server"
    ports:
      - "8000:8000"
    networks:
      app_net:
        # 固定子网ip，网段必须在子网络10.10.*.*
        ipv4_address: 10.10.10.3
    build:
      context: ./src
      # shm_size: '1gb'
      
 
networks:
  # 配置docker network
  app_net:
    driver: bridge
    ipam:
      config:
        # 子网络
        - subnet: 10.10.0.0/16
